# Generated by Django 5.2.1 on 2025-05-21 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrylog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name="Повне ім'я")),
                ('entered_at', models.DateTimeField(auto_now_add=True, verbose_name='Час входу')),
                ('exited_at', models.DateTimeField(blank=True, null=True, verbose_name='Час виходу')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Додав користувач')),
            ],
        ),
    ]
